name: HCSS_Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: linting
        run: util/checkwhite -n
        working-directory: crawl-ref/source
      - name: submodules
        run: git submodule update --init
      - name: setting terminal
        run: export TERM=xterm-256color
      - name: testing
        run: make debug test
        working-directory: crawl-ref/source
